cscare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cscareapp.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cscareapp/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

# app_name = "cscareapp"
urlpatterns = [
	path('', view_homepage, name='homepage'),
	path('register/', register, name = 'register'),
	path('add_donatur/', add_donatur, name='add_donatur'),
	path('tentang/', tentang, name='tentang'),
	path('testimoni/', testimoni, name='testimoni'),
	path('add_testimoni/', add_testimoni, name='add_testimoni'),
	path('program/<nama_program>/', program, name='program'),
	path('donasi/<nama_program>/', donasi, name = 'donasi'),
	path('add_donasi/<nama_program>/', add_donasi, name='add_donasi'),
	path('logout/', logout, name = 'logout'),
	path('donations/', donations, name = 'donations'),
]

cscareapp/models.py
from datetime import date
from django.db import models

# Create your models here.
class Accounts(models.Model):
    name = models.TextField(max_length=100)
    birth_date = models.DateField()
    email = models.EmailField(unique = True)
    password = models.TextField(max_length=20)

    def save(self, *args, **kwargs):
        tahun = int(self.birth_date.split('-')[0])
        bulan = int(self.birth_date.split('-')[1])
        tanggal = int(self.birth_date.split('-')[2])
        now = date.today()
        if (now.year > tahun):
            super(Accounts, self).save(*args, **kwargs)
        elif (now.year == tahun and now.month > bulan):
            super(Accounts, self).save(*args, **kwargs)
        elif (now.year == tahun and now.month == bulan and now.day > tanggal):
            super(Accounts, self).save(*args, **kwargs)


class Donations(models.Model):
    program = models.TextField(max_length = 100)
    donatur = models.TextField(max_length = 100)
    email = models.EmailField()
    uang = models.IntegerField()
    visibilitas = models.BooleanField(default = False)

class Disasters(models.Model):
    nama = models.TextField()
    deskripsi = models.TextField()
    foto = models.TextField()

class Testimoni(models.Model):
    nama = models.TextField()
    komentar = models.TextField()

    def as_dict(self):
        return {
            "nama": self.nama,
            "komentar": self.komentar
        }

cscareapp/forms.py
from django import forms

class Register_Form(forms.Form):
    name = forms.CharField(label = "Nama Lengkap", required = True, max_length = 100, widget=forms.TextInput(attrs= {'class' : 'form-control'}))
    birth_date = forms.DateField(label = "Tanggal Lahir", required = True, widget = forms.DateInput(attrs = {'type': 'date','class' : 'form-control'}))
    email = forms.EmailField(label = "Email", required = True, widget = forms.EmailInput(attrs = {'class' : 'form-control'}))
    password = forms.CharField(label = "Password", required = True, min_length = 8, widget = forms.PasswordInput(attrs = {'class' : 'form-control'}))

class Donation_Form(forms.Form):
    # program = forms.CharField(label = "Nama Program", required = True, widget = forms.TextInput(attrs= {'class' : 'form-control'}))
    # donatur = forms.CharField(label = "Nama Lengkap", required = True, max_length = 100, widget=forms.TextInput(attrs= {'class' : 'form-control'}))
    # email = forms.EmailField(label = "Email", required = True, widget = forms.EmailInput(attrs = {'class' : 'form-control'}))
    uang = forms.IntegerField(label = "Jumlah Rp", required = True,  widget=forms.TextInput(attrs= {'type': 'number','class' : 'form-control'}))
    visibilitas = forms.BooleanField(label = "Menampilkan Nama", required = False, widget = forms.CheckboxInput(attrs= {'class' : 'form-control'}))

class Testimoni_Form(forms.Form):
    komentar = forms.CharField(
        label = "Komentar anda mengenai kami?",
        required = True,
        widget = forms.Textarea(
        attrs = {
        'placeholder' : 'Bagaimana kesanmu berbagi dengan CSCare?',
        'class' : 'form-control',
        'data-length' : 300}))

cscareapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from .forms import *
from .models import *
from django.contrib.auth import logout as auth_logout

# Create your views here.
def get_response():
	lokasi = 'Sinar Perak Tower, Setiabudi, Jakarta South'
	nomor_hp = '085811916028'
	email = 'cscare@sinarperak.com'
	tentang_kami = 'Kami adalah komunitas mahasiswa yang ingin membantu saudara setanah air yang sedang dilanda musibah.'
	response = {'lokasi': lokasi, 'nomor_hp': nomor_hp, 'email': email, 'tentang_kami': tentang_kami}
	return response

def view_homepage(request):
	response = get_response()
	disaster = Disasters.objects.get(nama='Duka Palu, Duka Kita Bersama')
	response['current_program'] = disaster.nama
	response['dana_terkumpul'] = 99999999
	response['total_donatur'] = 10000
	response['disasters'] = Disasters.objects.exclude(nama=disaster.nama)
	response['range'] = range(2, 8)
	return render(request, 'Home Page.html', response)

def register(request):
	response = get_response()
	form = Register_Form()
	response['form'] = form
	return render(request, 'Register Page.html', response)

def program(request, nama_program):
	if request.user.is_authenticated:
		response = get_response()
		disaster = Disasters.objects.get(nama=nama_program)
		disasters = Disasters.objects.exclude(nama=nama_program)[0:3]
		response['nama_program'] = disaster.nama
		response['foto_program'] = disaster.foto
		response['deskripsi_program'] = disaster.deskripsi
		response['disasters'] = disasters
		response['range'] = range(2, 5)
		return render(request, 'Program Page.html', response)
	else:
		return HttpResponseRedirect('/register')

def add_donatur(request):
	form = Register_Form(request.POST or None)
	response = {}
	if(request.method == 'POST' and form.is_valid()):
		if(Accounts.objects.filter(email=request.POST['email']).count() == 0):
			response['name'] = request.POST['name']
			response['birth_date'] = request.POST['birth_date']
			response['email'] = request.POST['email']
			response['password'] = request.POST['password']
			new_donatur = Accounts(name = response['name'],
	            birth_date = response['birth_date'],
	            email = response['email'],
	            password = response['password'])
			new_donatur.save()
	return HttpResponseRedirect('/register')

def donasi(request, nama_program):
	response = get_response()
	disaster = Disasters.objects.get(nama=nama_program)
	disasters = Disasters.objects.exclude(nama=nama_program)[0:3]
	response['nama_program'] = disaster.nama
	response['form'] = Donation_Form()
	return render(request, 'Donasi Page.html', response)

def add_donasi(request, nama_program):
	form = Donation_Form(request.POST or None)
	response = {}
	if(request.method == 'POST' and form.is_valid()):
		response['program'] = nama_program
		response['donatur'] = request.user.id
		response['email'] = request.user.email
		response['uang'] = request.POST['uang']
		if('visibilitas' in request.POST):
			response['visibilitas'] = True
			new_donasi = Donations(program = response['program'],
			donatur = response['donatur'],
			email = response['email'],
			uang = response['uang'],
			visibilitas = response['visibilitas'])
		else:
			response['visibilitas'] = False
			new_donasi = Donations(program = response['program'],
			donatur = response['donatur'],
			email = response['email'],
			uang = response['uang'],
			visibilitas = response['visibilitas'])
		new_donasi.save()
	return HttpResponseRedirect('/donations')

def donations(request):
	response = get_response()
	daftar_donasi = Donations.objects.filter(donatur=str(request.user.id))
	response['daftar_donasi'] = daftar_donasi
	return render(request, 'Donations Page.html', response)

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/')

def tentang(request):
	response = get_response()
	response['form'] = Testimoni_Form()
	response['testimoni'] = Testimoni.objects.all()
	return render(request, 'About Page.html', response)

def testimoni(request):
	testi = list(Testimoni.objects.values())
	data = {
		'testi': testi
    }
	return JsonResponse(data)

def add_testimoni(request):
	if request.method == 'POST':
		nama = request.POST['nama']
		komentar = request.POST['komentar']
		testi = Testimoni(nama=nama, komentar=komentar)
		testi.save()
	return JsonResponse(testi.as_dict())

cscareapp/templates/cscareapp/About Page.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="about">
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center judul-testi">
                    <h4>Testimoni</h4>
                </div>
                <div class="carousel slide" data-ride="carousel" id="quote-carousel">
                    <!-- Bottom Carousel Indicators -->
                    <ol class="carousel-indicators" id="slide_num">

                    </ol>
                    <!-- Carousel Slides / Quotes -->
                    <div class="carousel-inner" id="testimoni_slider">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    {% if user.is_authenticated %}
    <div class = "container">
        <form id="form">
            {% csrf_token %}
            <input type="hidden" id="id_nama" value="{{ user.username }}">
            {{ form }}
            <div class = "text-center tombol">
                <button type="submit" class = "btn btn-primary btn-donasi-page">Submit</button>
            </div>
        </form>
    </div>
    {% endif %}
    <br>
</div>
{% endblock %}

cscareapp/templates/cscareapp/Donasi Page.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="donasi">
    <div class = "jumbotron background">
      <div class = "panel-donasi">
        <h2 class = "text-center">Donasi {{ nama_program }}</h2>
            <form action="{% url 'add_donasi' nama_program %}" method="POST" class = "thisform">
              {% csrf_token %}
              {{ form }}
            <div class = "text-center tombol">
                <input type="submit" value="Donasi" class = "btn btn-primary btn-donasi-page">
            </div>
          </form>
      </div>
  </div>
</div>
{% endblock %}

cscareapp/templates/cscareapp/Donations Page.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="content container table-responsive">
  <table class="table">
    <thead>
    <tr>
    <th>Nama Musibah</th>
    <th>Jumlah Donasi</th>
    </tr>
    </thead>
    <tbody>
    {% for donasi in daftar_donasi %}
    <tr>
    <td>{{ donasi.program }}</td>
    <td>Rp {{ donasi.uang }},00</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

cscareapp/templates/cscareapp/Home Page.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}


		<div class="bigimg">
		    <h2 class="text text-block">{{current_program}}</h2>
		    <a href="{% url 'program' 'Duka Palu, Duka Kita Bersama' %}">
				<button type="button" class="btn btn-success btn-md donasi-btn-home">
		    		Donasi Sekarang
				</button>
			</a>
		</div>
		<div class="container">
			<div class="row">
				{% for disaster in disasters %}
				  <div class="card col-xs-12 col-sm-6 col-md-4 other-row">
				  	<img class="card-img" src="{% static disaster.foto %}">
				  	<div class="card-body">
				  		<h4 class="card-title">{{disaster.nama}}</h4>
				  		<p class="card-text">{{disaster.deskripsi}}
				  		<a href="{% url 'program' disaster.nama %}" class="cont-read">...Lanjutkan membaca</a>
				  		</p>
				  	</div>
				  </div>
				{% endfor %}
			</div>
		</div>
		<div class="info-dana">
			<div class="container">
				<div class="row">
					<div class="col-md-6 text-center">
						<h2 class="text footer-text">
						Dana Terkumpul:<br>
						Rp {{dana_terkumpul}}</h2>
					</div>
					<div class="col-md-6 text-center">
						<h2 class="text footer-text">
						Total Donatur:<br>
						{{total_donatur}}
						</h2>
					</div>
				</div>
			</div>
		</div>
{% endblock %}

cscareapp/templates/cscareapp/Program Page.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

		<div class="program-body">
			<div class="container">
				<h1 class="text program-title">{{nama_program}}</h1>
				<div class="row">
					<img class="img-responsive col-md-6 program-img" src="{% static foto_program %}">
					<div class="col-md-6">
						<div class="row program-about">
							<p class="text program-about-text">
							{{deskripsi_program}}<br>
							Total Donasi:<br>
							{{donasi}}</p>
						</div>
						<div class="row">
							<button type="button" class="btn button-program">
								<a href="{% url 'donasi' nama_program %}">Donasi Sekarang</a>
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container program-others">
			<div class="row">
				{% for disaster in disasters %}
				  <div class="card col-xs-12 col-sm-6 col-md-4 other-row">
				  	<img class="card-img" src="{% static disaster.foto %}">
				  	<div class="card-body">
				  		<h4 class="card-title">{{disaster.nama}}</h4>
				  		<p class="card-text">{{disaster.deskripsi}}
				  		<a href="{% url 'program' disaster.nama %}" class="cont-read">...Lanjutkan membaca</a>
				  		</p>
				  	</div>
				  </div>
				{% endfor %}
			</div>
		</div>
{% endblock %}

cscareapp/templates/cscareapp/Register Page.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div class = "jumbotron reg">
  <div class = "fill">
    <h2 class = "text-center">Mendaftar Menjadi Donatur</h2>
        <form action="{% url 'add_donatur' %}" method="POST" class = "thisform">
          {% csrf_token %}
          {{ form }}
        <div class = "text-center tomtom">
            <input type="submit" value="Submit" class = "btn btn-donasi-page btn-primary">
        </div>
      </form>
      <div class="text-center">
        <a href="{% url 'social:begin' 'google-oauth2' %}" class="loginBtn loginBtn--google gotoms">
          <i class="fa fa-google"></i> Sign in with Google
        </a>
      </div>
  </div>
</div>
{% endblock %}

cscareapp/templates/cscareapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>CS Care</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Home Page.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Register Page.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Donasi Page.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/About Page.css' %}">
</head>

<body>
    <div class = "header">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" href="{% url 'homepage' %}">CS Care</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbardrop" href="#">
                            Program
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'program' 'Duka Palu, Duka Kita Bersama'%}">
                                Duka Palu, Duka Kita Bersama
                            </a>
                            <a class="dropdown-item" href="{% url 'program' 'Bangun Kembali Lombok'%}">
                                Bangun Kembali Lombok
                            </a>
                            <a class="dropdown-item" href="{% url 'program' 'Bangun Kembali Masjid di Pulau Seribu Masjid'%}">
                                Bangun Kembali Masjid di Pulau Seribu Masjid
                            </a>
                            <a class="dropdown-item" href="{% url 'program' 'Sekolah Darurat untuk Anak-anak Lombok'%}">
                                Sekolah Darurat untuk Anak-anak Lombok
                            </a>
                            <a class="dropdown-item" href="{% url 'program' 'Bangun Dapur Umum di Lombok'%}">
                                Bangun Dapur Umum di Lombok
                            </a>
                            <a class="dropdown-item" href="{% url 'program' 'Siaga Pangan di Lombok'%}">
                                Siaga Pangan di Lombok
                            </a>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="{% url 'tentang' %}">
                            Tentang
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                        <li><a class="nav-link" href="{% url 'donations' %}">
                            Daftar Donasi Saya
                        </a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li><p class="nav-link">Hello, {{ user.username }}</p></li>
                    <li><a class="nav-link" href="{% url 'logout' %}">Log out</a></li>
                    {% else %}
                    <li><a class="nav-link" href="{% url 'register' %}" id="register"><span class="fas fa-user"></span> Register</a></li>
                    {% endif %}
                </ul>
            </div>

		</nav>
    </div>

    <div class="content">
        {% block content%}
        {% endblock content %}
    </div>

    <div class="footer">
        <div class="row">
            <div class="col-sm-6 footer">
                <div class="row">
                    <h5 class="footer-text"><span class="fas fa-map-marked-alt"></span> {{lokasi}}</h5>
                </div>
                <div class="row">
                    <h5 class="footer-text"><span class="fas fa-phone"></span> {{nomor_hp}}</h5>
                </div>
                <div class="row">
                    <h5 class="footer-text"><span class="fas fa-at"></span> {{email}}</h5>
                </div>
            </div>
            <div class="col-sm-6">
                <h2 class="footer-text">Tentang kami:</h2>
                <h5 class="footer-text">{{tentang_kami}}</h5>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script type="application/javascript" src="{% static 'js/About Page.js' %}"></script>
</body>
</html>